# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lastgui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Browse = QtWidgets.QPushButton(self.groupBox)
        self.Browse.setObjectName("Browse")
        self.gridLayout_2.addWidget(self.Browse, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 2, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.showphantom = Label(self.splitter)
        self.showphantom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.showphantom.setFrameShape(QtWidgets.QFrame.Box)
        self.showphantom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.showphantom.setScaledContents(True)
        self.showphantom.setAlignment(QtCore.Qt.AlignCenter)
        self.showphantom.setObjectName("showphantom")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.t1 = PlotWidget(self.tab)
        self.t1.setObjectName("t1")
        self.verticalLayout.addWidget(self.t1)
        self.t2 = PlotWidget(self.tab)
        self.t2.setObjectName("t2")
        self.verticalLayout.addWidget(self.t2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.kspace = QtWidgets.QLabel(self.tab_2)
        self.kspace.setFrameShape(QtWidgets.QFrame.Box)
        self.kspace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kspace.setAlignment(QtCore.Qt.AlignCenter)
        self.kspace.setObjectName("kspace")
        self.verticalLayout_2.addWidget(self.kspace)
        self.constImage = QtWidgets.QLabel(self.tab_2)
        self.constImage.setFrameShape(QtWidgets.QFrame.Box)
        self.constImage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.constImage.setAlignment(QtCore.Qt.AlignCenter)
        self.constImage.setObjectName("constImage")
        self.verticalLayout_2.addWidget(self.constImage)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 3)
        self.flipangle = QtWidgets.QLineEdit(self.tab_2)
        self.flipangle.setMaximumSize(QtCore.QSize(16777215, 16))
        self.flipangle.setObjectName("flipangle")
        self.gridLayout.addWidget(self.flipangle, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.TR = QtWidgets.QLineEdit(self.tab_2)
        self.TR.setMaximumSize(QtCore.QSize(16777215, 16))
        self.TR.setObjectName("TR")
        self.gridLayout.addWidget(self.TR, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.TE = QtWidgets.QLineEdit(self.tab_2)
        self.TE.setMaximumSize(QtCore.QSize(16777215, 16))
        self.TE.setText("")
        self.TE.setObjectName("TE")
        self.gridLayout.addWidget(self.TE, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.Browse.setText(_translate("MainWindow", "Browse"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "128"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "64"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "32"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "2"))
        self.comboBox.setItemText(0, _translate("MainWindow", "PD"))
        self.comboBox.setItemText(1, _translate("MainWindow", "T1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "T2"))
        self.showphantom.setText(_translate("MainWindow", "Phantom"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.kspace.setText(_translate("MainWindow", "Kspace"))
        self.constImage.setText(_translate("MainWindow", "Reconstructed"))
        self.label_5.setText(_translate("MainWindow", "TE"))
        self.label_6.setText(_translate("MainWindow", "Flip Angle"))
        self.label_4.setText(_translate("MainWindow", "TR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

from pyqtgraph import PlotWidget
class Label(QtWidgets.QLabel):
    def __init__(self, parent=None):
        super(Label, self).__init__(parent=parent)
        self.paint = False
        self.paint1 = False
        self.x = 0
        self.y = 0
        self.count = 0
        self.point = []
        self.pixel = []
    def paintEvent(self, e):
        super().paintEvent(e)
        painter = QtGui.QPainter(self)
        painter.setRenderHint(QtGui.QPainter.Antialiasing)
        #if self.paint:
        for self.pixel in self.point:
            painter.setPen(QtGui.QPen(QtCore.Qt.cyan))
            painter.drawRect(self.pixel[0], self.pixel[1], 8, 8)