# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phantom_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1271, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Browse = QtWidgets.QPushButton(self.centralwidget)
        self.Browse.setObjectName("Browse")
        self.gridLayout.addWidget(self.Browse, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(10, 20))
        self.comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.showphantom = QtWidgets.QLabel(self.centralwidget)
        self.showphantom.setEnabled(True)
        self.showphantom.setMinimumSize(QtCore.QSize(512, 512))
        self.showphantom.setMaximumSize(QtCore.QSize(512, 512))
        self.showphantom.setObjectName("showphantom")
        self.gridLayout.addWidget(self.showphantom, 1, 0, 1, 3)
        self.T2 = QtWidgets.QTabWidget(self.centralwidget)
        self.T2.setEnabled(True)
        self.T2.setMinimumSize(QtCore.QSize(735, 735))
        self.T2.setMaximumSize(QtCore.QSize(425, 721))
        self.T2.setObjectName("T2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMaximumSize(QtCore.QSize(50, 50))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.t2 = PlotWidget(self.tab)
        self.t2.setMaximumSize(QtCore.QSize(512, 512))
        self.t2.setObjectName("t2")
        self.gridLayout_3.addWidget(self.t2, 3, 0, 1, 2)
        self.t1 = PlotWidget(self.tab)
        self.t1.setMaximumSize(QtCore.QSize(512, 512))
        self.t1.setObjectName("t1")
        self.gridLayout_3.addWidget(self.t1, 1, 0, 1, 2)
        self.T2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.constImage = QtWidgets.QLabel(self.tab_2)
        self.constImage.setMinimumSize(QtCore.QSize(200, 200))
        self.constImage.setMaximumSize(QtCore.QSize(520, 520))
        self.constImage.setScaledContents(True)
        self.constImage.setObjectName("constImage")
        self.gridLayout_2.addWidget(self.constImage, 0, 0, 1, 3)
        self.kspace = QtWidgets.QLabel(self.tab_2)
        self.kspace.setMaximumSize(QtCore.QSize(520, 520))
        self.kspace.setScaledContents(True)
        self.kspace.setObjectName("kspace")
        self.gridLayout_2.addWidget(self.kspace, 1, 0, 1, 1)
        self.flipangle = QtWidgets.QLineEdit(self.tab_2)
        self.flipangle.setObjectName("flipangle")
        self.gridLayout_2.addWidget(self.flipangle, 2, 0, 1, 1)
        self.TE = QtWidgets.QLineEdit(self.tab_2)
        self.TE.setObjectName("TE")
        self.gridLayout_2.addWidget(self.TE, 2, 1, 1, 1)
        self.TR = QtWidgets.QLineEdit(self.tab_2)
        self.TR.setObjectName("TR")
        self.gridLayout_2.addWidget(self.TR, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 2, 1, 1)
        self.T2.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.T2, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1271, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.T2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Browse.setText(_translate("MainWindow", "Browse"))
        self.comboBox.setItemText(0, _translate("MainWindow", "PD"))
        self.comboBox.setItemText(1, _translate("MainWindow", "T1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "T2"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "128"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "64"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "32"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "3"))
        self.showphantom.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "    T2"))
        self.label_4.setText(_translate("MainWindow", "    T1"))
        self.T2.setTabText(self.T2.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.constImage.setText(_translate("MainWindow", "TextLabel"))
        self.kspace.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "FA"))
        self.label_9.setText(_translate("MainWindow", "TE"))
        self.label_10.setText(_translate("MainWindow", "TR"))
        self.T2.setTabText(self.T2.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

from pyqtgraph import PlotWidget
class Label(QtWidgets.QLabel):
    def __init__(self, parent=None):
        super(Label, self).__init__(parent=parent)
        self.paint = False
        self.paint1 = False
        self.x = 0
        self.y = 0
        self.count = 0
        self.point = []
        self.pixel = []
    def paintEvent(self, e):
        super().paintEvent(e)
        painter = QtGui.QPainter(self)
        painter.setRenderHint(QtGui.QPainter.Antialiasing)
        #if self.paint:
        for self.pixel in self.point:
            painter.setPen(QtGui.QPen(QtCore.Qt.cyan))
            painter.drawRect(self.pixel[0], self.pixel[1], 8, 8)